### PR TITLE
Please update Factory (Get Mega Bot) and Factory (Get Money). And please add All Blooks In Game script. Thank you!

### PR DESCRIPTION
**Pull request by GREATEST9999**
Please update Factory (Get Mega Bot) and Factory (Get Money). And please add All Blooks In Game script. Thank you!

### CODE REVIEW

**Comment by Gsnipe1blookethacks** [comment]
Thank you GREATEST9999 for your comment I have fixed the issue that you have mentioned. 
Thanks, Gsnipe1blookethacks

**Comment by GREATEST9999** [comment]
Oh, and can you please fix the scripts for Crypto Hack (Get Crypto), Crypto Hack (Get Password), Gold Quest (Free Gold), Gold Quest (Chest ESP), Tower of Doom (Free Coins), Tower of Doom (Max Stats), Tower Of Doom Lower Enemy stats, Tower Defense (Set Game Round), Tower Defense (Kill Enemy), Tower Defense (Free Gold and Money), and Racing (Instant Win). 

List of scripts that need to be fixed.
The flood game is fixed too. So can you please add that to your hacks if you can?

**Comment by Gsnipe1blookethacks** [comment]
Yes I will fix all codes as soon as possible. I am currently on vacation. I get back tomorrow, I will fix it when I get back

**Comment by Gsnipe1blookethacks** [comment]
Also (as seen on security page) the codes will receive an update at 6 pm pacific time on Sunday.

**Comment by Gsnipe1blookethacks** [comment]
Since this issue has been resolved I will be deleting it. 

Thanks,Gsnipe1

**Pull request closed without merging**
